import { ExternalLinkIcon } from "lucide-react";

import type { ComponentApi } from "@/docs/api";
import { apiHighlight } from "@/docs/generated/api-highlight";

/**
 * A code token rendered with the same Shiki github highlighting as the Code
 * tabs (pre-generated by scripts/gen-api.mjs). Falls back to plain text.
 */
function HlCode({ children }: { children: string }) {
  const html = apiHighlight[children];
  return html ? (
    <code
      className="shiki font-mono text-xs"
      dangerouslySetInnerHTML={{ __html: html }}
    />
  ) : (
    <code className="font-mono text-xs text-foreground">{children}</code>
  );
}

/** Anatomy + notable props for a component, rendered below its variant previews. */
export function ApiReference({ api }: { api: ComponentApi }) {
  const partsHaveDescriptions = api.parts.some((p) => p.description);
  const props = api.props ?? [];
  const propsHaveDescriptions = props.some((p) => p.description);

  return (
    <section id="api-reference" className="flex scroll-mt-24 flex-col gap-4">
      <div className="flex flex-col gap-1">
        <h3 className="text-lg font-semibold tracking-tight">API reference</h3>
        {api.summary && (
          <p className="text-sm text-muted-foreground">{api.summary}</p>
        )}
        {api.base && (
          <a
            href={api.base.url}
            target="_blank"
            rel="noreferrer"
            className="inline-flex w-fit items-center gap-1 text-xs font-medium text-primary hover:underline dark:text-primary-emphasis"
          >
            Full props on {api.base.name}
            <ExternalLinkIcon className="size-3" />
          </a>
        )}
      </div>

      {/* Anatomy */}
      {api.parts.length > 0 && (
        <div className="flex flex-col gap-2">
          <span className="text-xs font-medium text-muted-foreground">Anatomy</span>
          {partsHaveDescriptions ? (
            <div className="overflow-hidden rounded-lg border border-border">
              <table className="w-full text-sm">
                <tbody>
                  {api.parts.map((p, i) => (
                    <tr
                      key={p.name}
                      className={i > 0 ? "border-t border-border" : undefined}
                    >
                      <td className="w-56 px-3 py-2 align-top">
                        <HlCode>{p.name}</HlCode>
                      </td>
                      <td className="px-3 py-2 align-top text-muted-foreground">
                        {p.description}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          ) : (
            <div className="flex flex-wrap gap-2 rounded-lg border border-border p-3">
              {api.parts.map((p) => (
                <span key={p.name} className="rounded-md bg-muted px-2 py-1">
                  <HlCode>{p.name}</HlCode>
                </span>
              ))}
            </div>
          )}
        </div>
      )}

      {/* Props */}
      {props.length > 0 && (
        <div className="flex flex-col gap-2">
          <span className="text-xs font-medium text-muted-foreground">Props</span>
          <div className="overflow-x-auto rounded-lg border border-border">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-border text-left text-xs text-muted-foreground">
                  <th className="px-3 py-2 font-medium">Part</th>
                  <th className="px-3 py-2 font-medium">Prop</th>
                  <th className="px-3 py-2 font-medium">Type</th>
                  <th className="px-3 py-2 font-medium">Default</th>
                  {propsHaveDescriptions && (
                    <th className="px-3 py-2 font-medium">Description</th>
                  )}
                </tr>
              </thead>
              <tbody>
                {props.map((p) => (
                  <tr
                    key={`${p.part}.${p.name}`}
                    className="border-t border-border align-top"
                  >
                    <td className="px-3 py-2">
                      <HlCode>{p.part}</HlCode>
                    </td>
                    <td className="px-3 py-2">
                      <HlCode>{p.name}</HlCode>
                    </td>
                    <td className="px-3 py-2 whitespace-nowrap">
                      <HlCode>{p.type}</HlCode>
                    </td>
                    <td className="px-3 py-2 whitespace-nowrap">
                      {p.default ? (
                        <HlCode>{p.default}</HlCode>
                      ) : (
                        <span className="text-xs text-muted-foreground">—</span>
                      )}
                    </td>
                    {propsHaveDescriptions && (
                      <td className="px-3 py-2 text-muted-foreground">
                        {p.description}
                      </td>
                    )}
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}
    </section>
  );
}
