// Extracts the static route list — one { group, slug } per docs section — from
// src/app/sections.tsx into plain data. sections.tsx is TSX that lazily imports
// every section, so the node scripts that need the list — prerender.mjs, which
// writes one HTML shell per route, and verify-docs.mjs — read this file instead.
//
// Output: src/docs/generated/routes.ts
//
// Parsing mirrors gen-api.mjs: top-level section entries are indented exactly
// four spaces, so `^\s{4}id:` / `^\s{4}group:` match sections but not the more
// deeply-indented `toc` item ids.

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { freshness, forced } from "./lib/stale.mjs";
import { groupSlug } from "./lib/sections.mjs";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");

// Skip the work when nothing this generator reads has moved (see lib/stale.mjs).
// `--force` / DOCS_GEN_FORCE=1 rebuilds regardless.
const stamp = freshness({
  name: "routes",
  inputs: ["src/app/sections.tsx", "scripts/gen-routes.mjs", "scripts/lib/sections.mjs"],
  outputs: ["src/docs/generated/routes.ts"],
});
if (stamp.fresh && !forced()) {
  console.log("gen-routes — up to date — skipped");
  process.exit(0);
}

const src = readFileSync(resolve(root, "src/app/sections.tsx"), "utf8");
const lines = src.split("\n");
const start = lines.findIndex((l) => l.includes("const sections: Section[]"));

const params = [];
let cur = null;
for (const l of lines.slice(start)) {
  const idm = l.match(/^\s{4}id:\s*"([^"]+)"/);
  if (idm) {
    cur = idm[1];
    continue;
  }
  if (cur) {
    const gm = l.match(/^\s{4}group:\s*"([^"]+)"/);
    if (gm) {
      params.push({ group: groupSlug(gm[1]), slug: cur });
      cur = null;
    }
  }
}

const outDir = resolve(root, "src/docs/generated");
mkdirSync(outDir, { recursive: true });
writeFileSync(
  resolve(outDir, "routes.ts"),
  "// AUTO-GENERATED by scripts/gen-routes.mjs — do not edit.\n" +
    "export const staticParams: { group: string; slug: string }[] = " +
    JSON.stringify(params, null, 2) +
    ";\n"
);
console.log(`gen-routes — ${params.length} routes`);

stamp.save();
