// Extracts the static route list — one { group, slug } per docs section — from
// src/app/sections.tsx into a server-safe module. sections.tsx is a "use client"
// module, so a server component (the [group]/[slug] route's generateStaticParams,
// which the static export needs) can't import its runtime values directly; it
// imports this generated data instead.
//
// Output: src/docs/generated/routes.ts
//
// Parsing mirrors gen-api.mjs: top-level section entries are indented exactly
// four spaces, so `^\s{4}id:` / `^\s{4}group:` match sections but not the more
// deeply-indented `toc` item ids.

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const src = readFileSync(resolve(root, "src/app/sections.tsx"), "utf8");
const lines = src.split("\n");
const start = lines.findIndex((l) => l.includes("const sections: Section[]"));

// Keep in sync with groupSlug() in src/app/sections.tsx.
const groupSlug = (g) => g.toLowerCase().replace(/\s+/g, "-");

const params = [];
let cur = null;
for (const l of lines.slice(start)) {
  const idm = l.match(/^\s{4}id:\s*"([^"]+)"/);
  if (idm) {
    cur = idm[1];
    continue;
  }
  if (cur) {
    const gm = l.match(/^\s{4}group:\s*"([^"]+)"/);
    if (gm) {
      params.push({ group: groupSlug(gm[1]), slug: cur });
      cur = null;
    }
  }
}

const outDir = resolve(root, "src/docs/generated");
mkdirSync(outDir, { recursive: true });
writeFileSync(
  resolve(outDir, "routes.ts"),
  "// AUTO-GENERATED by scripts/gen-routes.mjs — do not edit.\n" +
    "export const staticParams: { group: string; slug: string }[] = " +
    JSON.stringify(params, null, 2) +
    ";\n"
);
console.log(`gen-routes — ${params.length} routes`);
